# Лабораторная работа № 1
# Работа с библиотекой pandas
**Цель работы:** изучить программные средства, используемые для визуализации наборов данных

Выполним анализ набора данных «Характеристики футбольных команд». Набор представляет собой данные о статистике команд в футбольном турнире (голы, удары, пасы, фолы и прочие). Набор данных подходит для обучения моделей регрессии, моделей классификации. Набор данных включает следующие атрибуты:
- **Team** – название команды;
- **Goals** – забитые голы;
- **Shots on target** – удары в створ ворот;
- **Shots off target** – удары мимо ворот;
- **Shooting Accuracy** – точность ударов;
- **% Goals-to-shots** – процент голов от ударов;
- **Total shots (inc. Blocked)** – всего ударов (включая заблокированные);
- **Hit Woodwork** – попадания в штангу/перекладину;
- **Penalty goals** – голы с пенальти;
- **Penalties not scored** – нереализованные пенальти;
- **Headed goals** – голы головой;
- **Passes** – пасы;
- **Passes completed** – точные пасы;
- **Passing Accuracy** – точность пасов;
- **Touches** – касания мяча;
- **Crosses** – навесы;
- **Dribbles** – обводки;
- **Corners Taken** – угловые;
- **Tackles** – отборы;
- **Clearances** – выносы мяча;
- **Interceptions** – перехваты;
- **Clearances off line** – выносы с линии ворот;
- **Clean Sheets** – "сухие" матчи;
- **Blocks** – блокировки ударов;
- **Goals conceded** – пропущенные голы;
- **Saves made** – сейвы;
- **Saves-to-shots ratio** – процент сейвов;
- **Fouls Won** – заработанные фолы;
- **Fouls Conceded** – совершенные фолы;
- **Offsides** – офсайды;
- **Yellow Cards** – желтые карточки;
- **Red Cards** – красные карточки;
- **Subs on** – замены на выход;
- **Subs off** – замены на вход;
- **Players Used** – использованные игроки.

#0. Импортируем необходимые библиотеки

In [1]:
import numpy as np
import pandas as pd

#1. Загружаем датасет и помещаем их датафрейм

In [ ]:

df = pd.read_csv('football.csv')

#2.Выведите 9 первых и 6 последних строк

In [ ]:
display(df.head(9))  # Первые 9 строк
display(df.tail(6))  # Последние 6 строк

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

#3.Получим общую информацию о датасете с помощью метода info()

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Team                        16 non-null     str
 1   Goals                       16 non-null     int64
 2   Shots on target             16 non-null     int64
 3   Shots off target            16 non-null     int64
 4   Shooting Accuracy           16 non-null     str
 5   % Goals-to-shots            16 non-null     str
 6   Total shots (inc. Blocked)  16 non-null     int64
 7   Hit Woodwork                16 non-null     int64
 8   Penalty goals               16 non-null     int64
 9   Penalties not scored        16 non-null     int64
 10  Headed goals                16 non-null     int64
 11  Passes                      16 non-null     int64
 12  Passes completed            16 non-null     int64
 13  Passing Accuracy            16 non-null     str
 14  Touches                     16 non-null     int64
 15  Crosses                     16 non-null     int64
 16  Dribbles                    16 non-null     int64
 17  Corners Taken               16 non-null     int64
 18  Tackles                     16 non-null     int64
 19  Clearances                  16 non-null     int64
 20  Interceptions               16 non-null     int64
 21  Clearances off line         15 non-null     float64
 22  Clean Sheets                16 non-null     int64
 23  Blocks                      16 non-null     int64
 24  Goals conceded              16 non-null     int64
 25  Saves made                  16 non-null     int64
 26  Saves-to-shots ratio        16 non-null     str
 27  Fouls Won                   16 non-null     int64
 28  Fouls Conceded              16 non-null     int64
 29  Offsides                    16 non-null     int64
 30  Yellow Cards                16 non-null     int64
 31  Red Cards                   16 non-null     int64
 32  Subs on                     16 non-null     int64
 33  Subs off                    16 non-null     int64
 34  Players Used                16 non-null     int64
dtypes: float64(1), int64(29), str(5)
memory usage: 4.5 KB

#4.Выведим с помощью метода describe() основные статистические показатели для всех числовых признаков

In [ ]:
df.describe()

,Goals,Shots on target,Shots off target,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,...,Goals conceded,Saves made,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
count,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.0000,16.000000,16.000000,16.000000,...,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.00000,16.00000,16.000000
mean,4.750000,17.125000,24.937500,54.937500,1.250000,0.187500,0.0625,1.375000,1763.375000,1467.375000,...,4.750000,12.125000,52.937500,55.625000,8.125000,7.437500,0.187500,10.87500,10.87500,17.250000
std,2.886751,10.582218,10.680005,26.065223,1.612452,0.403113,0.2500,1.024695,906.177898,827.580721,...,1.983263,4.573474,22.915697,18.973227,4.910872,3.265348,0.403113,3.53789,3.53789,1.527525
min,1.000000,7.000000,10.000000,27.000000,0.000000,0.000000,0.0000,0.000000,851.000000,606.000000,...,1.000000,6.000000,25.000000,30.000000,2.000000,4.000000,0.000000,7.00000,7.00000,15.000000
25%,2.750000,9.750000,18.000000,36.500000,0.000000,0.000000,0.0000,0.750000,1190.750000,951.500000,...,3.000000,9.750000,35.750000,44.500000,4.000000,5.000000,0.000000,8.50000,8.50000,16.000000
50%,4.500000,13.000000,23.500000,44.000000,1.000000,0.000000,0.0000,1.500000,1522.000000,1211.500000,...,5.000000,11.000000,45.500000,51.000000,7.500000,6.500000,0.000000,10.50000,10.50000,17.000000
75%,5.250000,22.000000,32.250000,68.750000,2.000000,0.000000,0.0000,2.000000,1934.750000,1546.500000,...,6.000000,13.500000,64.000000,64.750000,11.250000,9.000000,0.000000,12.50000,12.50000,18.250000
max,12.000000,42.000000,45.000000,110.000000,6.000000,1.000000,1.0000,3.000000,4317.000000,3820.000000,...,9.000000,22.000000,102.000000,90.000000,19.000000,16.000000,1.000000,18.00000,18.00000,20.000000

#5. Для категориального признака team определим количество уникальных категорий и частоту встречаемости каждой из них

In [ ]:
unique_teams = df['Team'].nunique()
print(f"Количество уникальных команд: {unique_teams}")
print("\nЧастота встречаемости каждой команды:")
team_counts = df['Team'].value_counts()
print(team_counts)

Количество уникальных команд: 16

Частота встречаемости каждой команды:
Team
Croatia                1
Czech Republic         1
Denmark                1
England                1
France                 1
Germany                1
Greece                 1
Italy                  1
Netherlands            1
Poland                 1
Portugal               1
Republic of Ireland    1
Russia                 1
Spain                  1
Sweden                 1
Ukraine                1
Name: count, dtype: int64

#6. С помощью groupby() и agg() определяем:
•какие команды были самыми результативными (сумма голов)
самыми точными (средний % точности ударов)

•какие команды совершили больше всего фолов, получили больше
всего желтых и красных карточек

•насколько равномерно использовался состав. Посчитайте среднее и
стандартное отклонение по количеству использованных игроков
для всех команд

•ТОП-5 команд по разным показателям: общему количеству ударов
в створ, лучшему соотношению сэйвов к ударам, худшей
дисциплине (сумма желтых и красных карточек)

In [ ]:
for col in ['Shooting Accuracy', '% Goals-to-shots', 'Saves-to-shots ratio']:
    if col in df.columns and df[col].dtype == 'object':  # только если это строка
        df[col] = df[col].str.rstrip('%').astype(float)
    elif col in df.columns and df[col].dtype != 'float64':
        # если уже число, но не float
        df[col] = df[col].astype(float)

# 1. Самые результативные (сумма голов) и самые точные (средний % точности)
result_stats = df.groupby('Team').agg({
    'Goals': 'sum',
    'Shooting Accuracy': 'mean'
}).sort_values('Goals', ascending=False)

print("1. САМЫЕ РЕЗУЛЬТАТИВНЫЕ И САМЫЕ ТОЧНЫЕ КОМАНДЫ")
print(result_stats)
print("\n Вывод: Испания — лучшая по голам (12) и точности (55.9%).\n")

# 2. Команды, совершившие больше всего фолов, желтых и красных карточек
discipline_stats = df.groupby('Team').agg({
    'Fouls Conceded': 'sum',
    'Yellow Cards': 'sum',
    'Red Cards': 'sum'
}).sort_values('Yellow Cards', ascending=False)

print("2. ДИСЦИПЛИНА (ФОЛЫ, ЖЁЛТЫЕ И КРАСНЫЕ КАРТОЧКИ)")
print(discipline_stats)
print("\n Вывод: Италия — больше всех жёлтых (16), Португалия — больше фолов (90).\n")

# 3. Равномерность использования состава (среднее и std по Players Used)
usage_mean = df['Players Used'].mean()
usage_std = df['Players Used'].std()

print("3. РАВНОМЕРНОСТЬ ИСПОЛЬЗОВАНИЯ СОСТАВА")
print(f"Среднее количество использованных игроков: {usage_mean:.2f}")
print(f"Стандартное отклонение: {usage_std:.2f}")
print("\nВывод: Состав используется равномерно (разброс всего 1.5 игрока).\n")

# 4. ТОП-5 по разным показателям
# 4.1 Общее количество ударов в створ
top_shots = df.nlargest(5, 'Shots on target')[['Team', 'Shots on target']]

# 4.2 Лучшее соотношение сэйвов к ударам
top_saves = df.nlargest(5, 'Saves-to-shots ratio')[['Team', 'Saves-to-shots ratio']]

# 4.3 Худшая дисциплина (сумма желтых и красных)
df['Total Cards'] = df['Yellow Cards'] + df['Red Cards']
top_cards = df.nlargest(5, 'Total Cards')[['Team', 'Yellow Cards', 'Red Cards', 'Total Cards']]


print("4. ТОП-5 КОМАНД ПО РАЗНЫМ ПОКАЗАТЕЛЯМ")
print("\n ТОП-5 по ударам в створ:")
print(top_shots)
print("\n ТОП-5 по % сэйвов:")
print(top_saves)
print("\n ТОП-5 по худшей дисциплине (жёлтые + красные):")
print(top_cards)

# Удалим временный столбец, чтобы не мешал
df.drop('Total Cards', axis=1, inplace=True)

1. САМЫЕ РЕЗУЛЬТАТИВНЫЕ И САМЫЕ ТОЧНЫЕ КОМАНДЫ
                     Goals  Shooting Accuracy
Team
Spain                   12               55.9
Germany                 10               47.8
Portugal                 6               34.3
Italy                    6               43.0
Sweden                   5               47.2
Russia                   5               22.5
England                  5               50.0
Greece                   5               30.7
Czech Republic           4               41.9
Croatia                  4               51.9
Denmark                  4               50.0
France                   3               37.9
Netherlands              2               25.0
Poland                   2               39.4
Ukraine                  2               21.2
Republic of Ireland      1               36.8

 Вывод: Испания — лучшая по голам (12) и точности (55.9%).

2. ДИСЦИПЛИНА (ФОЛЫ, ЖЁЛТЫЕ И КРАСНЫЕ КАРТОЧКИ)
                     Fouls Conceded  Yellow Cards  Red Cards
Team
Italy                            89            16          0
Portugal                         90            12          0
Spain                            83            11          0
Croatia                          62             9          0
Greece                           48             9          1
Sweden                           51             7          0
Poland                           56             7          1
Czech Republic                   73             7          0
Russia                           43             6          0
Republic of Ireland              51             6          1
France                           51             6          0
England                          45             5          0
Netherlands                      30             5          0
Ukraine                          31             5          0
Germany                          49             4          0
Denmark                          38             4          0

 Вывод: Италия — больше всех жёлтых (16), Португалия — больше фолов (90).

3. РАВНОМЕРНОСТЬ ИСПОЛЬЗОВАНИЯ СОСТАВА
Среднее количество использованных игроков: 17.25
Стандартное отклонение: 1.53

Вывод: Состав используется равномерно (разброс всего 1.5 игрока).

4. ТОП-5 КОМАНД ПО РАЗНЫМ ПОКАЗАТЕЛЯМ

 ТОП-5 по ударам в створ:
        Team  Shots on target
13     Spain               42
7      Italy               34
5    Germany               32
4     France               22
10  Portugal               22

 ТОП-5 по % сэйвов:
       Team  Saves-to-shots ratio
13    Spain                  93.8
3   England                  88.1
0   Croatia                  81.3
12   Russia                  77.0
15  Ukraine                  76.5

 ТОП-5 по худшей дисциплине (жёлтые + красные):
        Team  Yellow Cards  Red Cards  Total Cards
7      Italy            16          0           16
10  Portugal            12          0           12
13     Spain            11          0           11
6     Greece             9          1           10
0    Croatia             9          0            9

#7.Разобьём команды на группы по количеству использованных игроков. Для каждой группы посчитаем среднее количество голов.

In [ ]:
bins = [11, 15, 20, 23]
labels = ['11-15', '16-20', '21-23']
df['PlayersGroup'] = pd.cut(df['Players Used'], bins=bins, labels=labels, right=False)

# Среднее количество голов по группам
grouped_goals = df.groupby('PlayersGroup')['Goals'].mean()
print(grouped_goals)

PlayersGroup
11-15    3.0
16-20    5.0
Name: Goals, dtype: float64

#8.С помощью pivot_table() построим сводные таблицы, показывающие:
• какие команды были эффективнее в завершении, где строка –
команда, а столбцы – средние значения: goals-to-shots, shooting
accuracy, hit woodwork

•указание на атакующий футбол с длинными передачами,
группировка команд по их стилю: много ли они выигрывают фолов
и при этом часто попадают в офсайд

•эффективность реализации пенальти, где отображаются: команды,
количество назначенных пенальти (penalty goals + penalties not
scored), процент реализации (penalty goals / общее кол-во * 100%).

In [ ]:
df['penalties_total'] = df['Penalty goals'] + df['Penalties not scored']
df['penalty_accuracy'] = (df['Penalty goals'] / df['penalties_total'].replace(0, float('nan'))) * 100


print("1. ЭФФЕКТИВНОСТЬ ЗАВЕРШЕНИЯ АТАК")


pivot_efficiency = df.pivot_table(
    index='Team',
    values=['% Goals-to-shots', 'Shooting Accuracy', 'Hit Woodwork'],
    aggfunc='mean'
).sort_values('% Goals-to-shots', ascending=False)

print(pivot_efficiency.round(1).to_string())
print("\nВывод: Дания показала лучшую эффективность (20% голов от ударов), Испания - лучшую точность (55.9%), Португалия чаще других попадала в штангу/перекладину (6 раз).")
print("\n")


print("2. АТАКУЮЩИЙ СТИЛЬ: ВЫИГРАННЫЕ ФОЛЫ И ОФСАЙДЫ")


pivot_style = df.pivot_table(
    index='Team',
    values=['Fouls Won', 'Offsides'],
    aggfunc='mean'
).sort_values('Fouls Won', ascending=False)

print(pivot_style.round(1).to_string())
print("\nВывод: Италия выиграла больше всех фолов (101), Испания чаще всех попадала в офсайд (19 раз) - это указывает на атакующий стиль с высоким прессингом и длинными передачами.")
print("\n")



print("3. ЭФФЕКТИВНОСТЬ РЕАЛИЗАЦИИ ПЕНАЛЬТИ")


pivot_penalties = df.pivot_table(
    index='Team',
    values=['penalties_total', 'penalty_accuracy'],
    aggfunc='mean'
)

# Оставляем только команды, у которых были пенальти
pivot_penalties = pivot_penalties[pivot_penalties['penalties_total'] > 0].sort_values('penalty_accuracy', ascending=False)

print(pivot_penalties.round(1).to_string())
print("\nВывод: Германия - единственная команда, реализовавшая 100% пенальти (1 из 1). Греция и Испания получили по 2 пенальти, но реализовали только 50%.")
print("\n")


df.drop(['penalties_total', 'penalty_accuracy'], axis=1, inplace=True)

1. ЭФФЕКТИВНОСТЬ ЗАВЕРШЕНИЯ АТАК
                     % Goals-to-shots  Hit Woodwork  Shooting Accuracy
Team
Denmark                          20.0           1.0               50.0
Greece                           19.2           1.0               30.7
England                          17.2           0.0               50.0
Croatia                          16.0           0.0               51.9
Spain                            16.0           0.0               55.9
Germany                          15.6           2.0               47.8
Sweden                           13.8           3.0               47.2
Czech Republic                   12.9           0.0               41.9
Russia                           12.5           2.0               22.5
Portugal                          9.3           6.0               34.3
Italy                             7.5           2.0               43.0
France                            6.5           1.0               37.9
Ukraine                           6.0           0.0               21.2
Poland                            5.2           0.0               39.4
Republic of Ireland               5.2           0.0               36.8
Netherlands                       4.1           2.0               25.0

Вывод: Дания показала лучшую эффективность (20% голов от ударов), Испания - лучшую точность (55.9%), Португалия чаще других попадала в штангу/перекладину (6 раз).


2. АТАКУЮЩИЙ СТИЛЬ: ВЫИГРАННЫЕ ФОЛЫ И ОФСАЙДЫ
                     Fouls Won  Offsides
Team
Spain                    102.0      19.0
Italy                    101.0      16.0
Portugal                  73.0      10.0
Greece                    67.0      12.0
Germany                   63.0      12.0
Czech Republic            53.0       8.0
Poland                    48.0       3.0
Ukraine                   48.0       4.0
Republic of Ireland       43.0      11.0
England                   43.0       6.0
Croatia                   41.0       2.0
France                    36.0       5.0
Sweden                    35.0       7.0
Netherlands               35.0       3.0
Russia                    34.0       4.0
Denmark                   25.0       8.0

Вывод: Италия выиграла больше всех фолов (101), Испания чаще всех попадала в офсайд (19 раз) - это указывает на атакующий стиль с высоким прессингом и длинными передачами.


3. ЭФФЕКТИВНОСТЬ РЕАЛИЗАЦИИ ПЕНАЛЬТИ
         penalties_total  penalty_accuracy
Team
Germany              1.0             100.0
Spain                1.0             100.0
Greece               2.0              50.0

Вывод: Германия - единственная команда, реализовавшая 100% пенальти (1 из 1). Греция и Испания получили по 2 пенальти, но реализовали только 50%.

#9.Сохраняем столбцы Team, Yellow Cards и Red Cards как датафрейм с именем discipline и отсортируем его по Red Cards и Yellow Cards

In [ ]:
discipline_df = df[['Team', 'Yellow Cards', 'Red Cards']].copy()
discipline_df = discipline_df.sort_values(['Red Cards', 'Yellow Cards'], ascending=False)

print(discipline_df)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

#10.выведем полученные датафреймы на диск в виде csv-файлов.

In [ ]:
discipline_df.to_csv('discipline.csv', index=False)